-- ============================================================
-- OXIDIAN / CARMOCREAM
-- Canonical database schema index
-- Fecha de consolidacion: 2026-04-24
-- ============================================================
--
-- Este archivo funciona como punto canonico de referencia del esquema
-- actual mientras la ejecucion operativa sigue dividida en migraciones.
--
-- Migraciones activas:
--   0001_hierarchy_foundation.sql
--   0002_chatbot_authorization.sql
--   0003_jwt_claims_hook.sql
--   0004_fix_42803.sql
--   0004_patch_functions.sql
--   0005_testing_readiness.sql
--   0006_fix_rls_auth_errors.sql
--   0007_fix_security_and_missing_tables.sql
--   0008_plans_and_feature_overrides.sql
--   0009_fix_tenants_rls_tenant_owner.sql
--   0010_backfill_tenant_subscriptions.sql
--   0011_fix_landing_requests_service_role_grants.sql
--   0012_store_modules_column.sql
--   0015_orders_tracking_columns.sql
--   0013_add_missing_templates_and_fixes.sql   ← Templates booking/express
--   0014_orders_and_staff_rls.sql             ← RLS completo staff/orders
--   0016_branch_operations_support.sql        ← Combos, caja y columnas operativas faltantes
--
-- Regla de trabajo:
--   - cualquier nueva funcionalidad con datos debe reflejarse aqui primero
--   - luego debe aterrizarse en una migracion incremental dentro de /supabase
--
-- Estado actual verificado:
--   - existe la jerarquia tenant -> store -> branch
--   - existe user_memberships para control de acceso jerarquico
--   - existen funciones para claims JWT y autorizacion por alcance
--   - stores.id sigue siendo texto tipo slug en este workspace
--   - existe public.categories como catalogo base por store y products.category_id
--   - orders.branch_id existe y order_number ya es entero
--   - combos, cash_entries y daily_sales_summary deben existir fuera de RESET_COMPLETE
--   - coupons necesita max_uses y ventana de validez para promociones reales
--   - tenant_subscriptions incluye feature_overrides, notes, plan_id starter y status
--   - el proyecto remoto de Supabase no parece tener activadas todas las
--     policies/grants esperadas, aunque las migraciones locales si las definen
--   - landing_requests requiere grant efectivo para service_role porque el
--     backend Flask crea leads con la key server-side
--
-- Entidades base esperadas
-- ============================================================
--
-- public.tenants
-- public.stores
-- public.branches
-- public.user_memberships
-- public.store_templates
-- public.store_plans
-- public.account_activations
-- public.chatbot_portable_pings
-- public.chatbot_authorization_log
-- public.tenant_subscriptions
-- public.landing_requests
--
-- Tablas de dominio con scope esperado
-- ============================================================
--
-- settings
-- config_tienda
-- store_settings
-- store_process_profiles
-- store_runtime_profiles
-- categories
-- products
-- combos
-- toppings
-- topping_categories
-- orders
-- stock_items
-- stock_item_products
-- coupons
-- affiliates
-- affiliate_applications
-- staff_users
-- cash_entries
-- daily_sales_summary
-- loyalty_rewards
-- reviews
-- visitors
-- chatbot_notifications
-- chatbot_conversations
-- oxidian_checkout_sessions
-- domain_mappings
-- store_niche_templates
-- tenant_subscriptions
-- store_plans
-- landing_requests
--
-- Funciones de seguridad esperadas
-- ============================================================
--
-- public.current_request_claim(text)
-- public.current_request_app_role()
-- public.current_request_tenant_id()
-- public.current_request_store_id()
-- public.current_request_branch_id()
-- public.is_super_admin()
-- public.can_access_scope(uuid, text, uuid)
-- public.custom_jwt_claims(jsonb)
-- public.make_super_admin(text)
-- public.invite_member(...)
-- public.revoke_member(...)
-- public.get_my_membership()
-- public.get_store_modules(text)
-- public.get_store_features(text)
-- public.apply_niche_preset(text, uuid, text)
--
-- Politicas RLS esperadas
-- ============================================================
--
-- tenants: super admin full access + lectura por tenant propio
-- stores: lectura publica + gestion por alcance
-- branches: lectura publica + gestion por alcance
-- user_memberships: super admin full access + tenant owner manage
-- store_templates: lectura publica de templates activos
-- store_plans: lectura publica de planes activos
-- categories: lectura publica del catalogo base por store
-- tenant_subscriptions: lectura por tenant y control total por super admin
-- landing_requests: insercion publica + gestion por super admin
--   + grant efectivo para service_role desde backend
--
-- Nota operativa importante
-- ============================================================
--
-- La fuente mas completa observada hoy para reconstruir el esquema es:
--   supabase/migrations/RESET_COMPLETE.sql
--
-- La migracion `0005_testing_readiness.sql` ya no es una capa de compatibilidad:
-- consolida el esquema canonico que falta respecto a RESET_COMPLETE.sql para:
--   - pipeline comercial (`landing_requests`)
--   - suscripciones por tenant (`tenant_subscriptions`)
--   - catalogo canonico de planes (`store_plans`)
--   - resolucion de modulos y presets (`get_store_modules`, `get_store_features`,
--     `apply_niche_preset`)
--
-- Los archivos 0004_fix_42803.sql, 0004_patch_functions.sql y
-- 0005_testing_readiness.sql deben revisarse junto con RESET_COMPLETE.sql
-- antes de ejecutar cambios en un entorno nuevo.
